### PR TITLE
Update Alamofire version to 4.8.x

### PR DESCRIPTION
**Pull request by AndreiEvstratenko**
# Pull Request

## Description

Updated Alamofire version to 4.8.x manually. I tested it and everything works ok. If we don't want update it manually (next time we run swagger codegen may be will break) this PR can help @RomanFrom710 to see what he needs to change in templates of the codegen.

### Motivation and Context

- closes #2067 

### Types of changes

- [ ] Bug fix
- [ ] New feature
- [x] Maintenance

### CODE REVIEW

**Comment by brentchow** [comment]
Does this break Swagger Codegen?

**Comment by AndreiEvstratenko** [comment]
> Does this break Swagger Codegen?

@RomanFrom710

**Comment by RomanFrom710** [comment]
Existing code changes can't break it. We'll just need to make respective changes of codegen templates, so this PR won't get lost after library generating

**Comment by brentchow** [comment]
@romanfrom710 want to help @andreievstratenko with this branch? It would be beneficial to show Andrei how to update the libraries and deploy updates.

**Comment by RomanFrom710** [comment]
Sure

**Pull request merged**
